name: Pull requests check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x.x
          cache: npm
      - run: npm ci
      - run: npm run lint
